export const UPDATING_SEARCH_VALUE = 'UPDATING_SEARCH_VALUE';
export const FETCH_GEMS = 'FETCH_GEMS';
export const FETCH_GEMS_START = 'FETCH_IMAGE_START';
export const FETCH_GEMS_SUCCESSFUL = 'FETCH_GEMS_SUCCESSFUL';
export const FETCH_GEMS_FAILED = 'FETCH_GEMS_FAILED';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
